spring:
    datasource:
      url: jdbc:mysql://localhost:3306/osahaneat
      username: root
      password: Huynhphu1998
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  privateKey: 5xck8gwDNbfA8iJzTNcyQPNkCY0z7rqHeVXTKttnWCg=